version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    init: true
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
