version: '3.9'

services:
  redis:
    image: redis
    container_name: redis
    init: true
    restart: unless-stopped
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis_bulk_loader:
    build:
      context: ../..
      dockerfile: Dockerfile.bulkloader
    container_name: redis_bulk_loader
    links:
      - redis
