version: "3.9"

services:
  redis:
    extends:
      file: base.yml
      service: redis

  goprom:
    build:
      context: ../..
    container_name: goprom
    ports:
      - "8080:8080"
    volumes:
      - promotions
    depends_on:
      - redis

volumes:
  promotions:
