version: "3.9"

services:
  redis:
    extends:
      file: base.yml
      service: redis

  api:
    build:
      context: ../..
    container_name: api
    environment:
      DEBUG: true
    ports:
      - "8080:8080"
    links:
      - redis

  loader:
    build:
      context: ../..
      dockerfile: Dockerfile.bulkloader
    container_name: loader
    environment:
      DEBUG: true
      PROMOTIONS: /data/promotions.csv
      PROMOTIONS_CMDS: /data/promotions_commands.txt
    volumes:
      - ../../data:/data
    links:
      - redis
