FROM golang:1.18 as build

WORKDIR /app

COPY go.mod go.sum Makefile ./
RUN make download
COPY . .
RUN make build-loader

# ---

FROM ubuntu

COPY --from=build /app/bin /
COPY cmd/loader/promotions_cron.sh /etc/cron.d/promotions_cron.sh

RUN apt-get update && apt-get -y install \
    cron \
    redis

RUN chmod 0644 /etc/cron.d/promotions_cron.sh && \
    crontab /etc/cron.d/promotions_cron.sh && \
    touch /var/log/cron.log && \
    mkdir -p /data

CMD cron && tail -f /var/log/cron.log
