global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: goprom_api
    metrics_path: /metrics
    static_configs:
      - targets: [ "api:8080" ]

  - job_name: prometheus
    scrape_interval: 1m
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: node
    static_configs:
      - targets: [ "node-exporter:9100" ]
